### ISSUE TITLE
Video feed flickers and is mostly green

### ISSUE THREAD

**Issue by nickgitnick** [am3n/RTSP-Client-Android#8]
The feed is mostly green, but periodically flickers in color.  The image is distorted.  Anything I can do to fix this?  

![image](https://github.com/am3n/RTSP-Client-Android/assets/33471488/677d20e6-4dc6-4c63-8c7e-ea94fc328236)

**Comment by am3n** [comment]
Hi @nickgitnick, it might be possible to resolve the issue by changing the codec.
check YuvFormat.NV21 on [link](https://github.com/am3n/RTSP-Client-Android?tab=readme-ov-file#4-you-can-still-use-library-with-h264-to-yuv-bytearray-decoding)

**Comment by am3n** [comment]
Fixed https://github.com/am3n/RTSP-Client-Android/releases/tag/5.0.0
